apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-service
  namespace: microservice
  labels:
    project: elasticsearch-service
    group: com.laegler.microservice
    provider: thlaegler
    version: 1.0.0-SNAPSHOT
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: elasticsearch-service
        image: elasticsearch-service:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 8080
      restartPolicy: Always
      terminationGracePeriodSeconds: 30