apiVersion: v1
kind: Service
metadata:
  name: microservice-es
  namespace: microservice
  labels:
    project: microservice-es
    group: com.laegler.microservice
    provider: thlaegler
    version: 1.0.0-SNAPSHOT
spec:
  selector:
    project: microservice-es
  ports:
  - name: http
    port: 9200
  - name: admin
    port: 9300